### PR TITLE
First aid to project page

### PR DESCRIPTION
**Pull request by bajiat**
Removing API Umbrella screenshots and buttons for getting API key, adding text about contributing, adding brief feature description, adding button to go to apinf.io

### CODE REVIEW

**Comment by bajiat** [comment]
Ready for review

**Comment by philippeluickx** [comment]
I get 2 error messages in console, both
`Failed to load resource: the server responded with a status of 404 (File not found)`

- http://localhost:8000/assets/img/bg01.jpg
- http://localhost:8000/assets/stylesheets/embed-6b4826ee.css

**Comment by philippeluickx** [comment]
When clicking the CTA button, we get a modal with

> Sign up for an application programming interface (API) key to access and use web services available on the **Data.gov developer network**.

Not sure what data.gov is about?

**Comment by philippeluickx** [comment]
Suggestion: we could rename the CTA "Discover apinf.io" instead of "go to tool"?

**Comment by philippeluickx** [comment]
Suggestion: security features for API owner (data limiting, rate throttling, distribution of keys, monitoring)

**Comment by philippeluickx** [comment]
Suggestion: make every mention of apinf clickable and redirect (new tab) to apinf.io

**Comment by philippeluickx** [comment]
Huge improvement, looks good!

**Pull request merged**
